allowBuilds:
  esbuild: true
  workerd: true
minimumReleaseAgeExclude:
  - "@cloudflare/workerd-darwin-64@1.20260930.2"
  - "@cloudflare/workerd-darwin-arm64@1.20260930.2"
  - "@cloudflare/workerd-linux-64@1.20260930.2"
  - "@cloudflare/workerd-linux-arm64@1.20260930.2"
  - "@cloudflare/workerd-windows-64@1.20260930.2"
  - hono@4.13.12
  - miniflare@5.20260930.0-alpha
  - workerd@1.20260930.2
  - wrangler@4.145.0
  - cf@1.0.0-beta.6
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@1.0.0
  vite-plus: 1.0.0
overrides:
  vite@*: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
