import { defineConfig } from "vite-plus";
export default defineConfig({
  fmt: {
    ignorePatterns: [
      "**/dist/**",
      "**/evidence/**",
      "**/.cloudflare/**",
      "**/test-results/**",
      "pnpm-lock.yaml",
      "CHANGELOG.md", // Generated by release-please; its formatter owns this file.
    ],
  },
  lint: {
    jsPlugins: [{ name: "vite-plus", specifier: "vite-plus/oxlint-plugin" }],
    rules: { "vite-plus/prefer-vite-plus-imports": "error" },
    options: { typeAware: true, typeCheck: true },
  },
  test: { include: ["tests/*.test.ts"] },
});
