/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false app/worker-env.d.ts` (hash: 1c0a08f328c1b33b7816a3c96439c80f)
interface __BaseEnv_Env {
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("../dist/worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
